ALTER TABLE IF EXISTS "GuildConfigs"
    ADD COLUMN IF NOT EXISTS "MiniWarnExpireHours" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE IF EXISTS "GuildConfigs"
    ADD COLUMN IF NOT EXISTS "MiniWarnExpireAction" INTEGER NOT NULL DEFAULT 0;
