ALTER TABLE "ChatTriggers"
    ADD COLUMN IF NOT EXISTS "IsDisabled"          BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS "AdditionalResponses" TEXT    NULL,
    ADD COLUMN IF NOT EXISTS "ResponseMode"        INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "RoundRobinIndex"     INTEGER NOT NULL DEFAULT 0;
