files:
  - source: /src/Mewdeko/data/strings/commands/en-US/*.yml
    translation: /src/Mewdeko/data/strings/commands/%locale%/%original_file_name%
  - source: /src/Mewdeko/data/strings/responses/en-US/*.json
    translation: /src/Mewdeko/data/strings/responses/%locale%/%original_file_name%
