global using Discord;
global using Discord.Webhook;
global using Discord.WebSocket;
global using Mewdeko.Database;
global using Mewdeko.Common;
global using Mewdeko.Common.Replacements;
global using Mewdeko.Database.Extensions;
global using Mewdeko.Database.Models;
global using Mewdeko.Extensions;
global using System.Threading.Channels;
global using Mewdeko.Services;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using NonBlocking;
global using System.Linq;
global using EventHandler = Mewdeko.Services.Impl.EventHandler;