<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
    <OutputType>exe</OutputType>
    <RuntimeIdentifiers>win-x86;win-x64;linux-x64;linux-arm</RuntimeIdentifiers>
    <Nullable>annotations</Nullable>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <ApplicationIcon>Mewdeko.ico</ApplicationIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <!-- god i hate this  -->
    <!-- <WarningsAsErrors>CS1591</WarningsAsErrors> -->
  </PropertyGroup>


  <!--    DO NOT DELETE   -->
  <!--    happy pride 🏳️‍⚧️ 🏳️‍🌈-->
<!-- don't delete also means don't replace with happy pride sylv -->
  <ItemGroup>
    <PackageReference Include="Claudia" Version="1.3.1" />
    <!-- <PackageReference Include="Discord.Net.WebSocket" Version="3.17.2" />
    <PackageReference Include="Discord.Net.Rest" Version="3.17.2" />
    <PackageReference Include="Discord.Net.Webhook" Version="3.17.2" />
    <PackageReference Include="Discord.Net.Interactions" Version="3.17.2" />
    <PackageReference Include="Discord.Net.Commands" Version="3.17.2" /> --> 
    <ProjectReference Include="../../../../dnet-dctk/src/Discord.Net.WebSocket/Discord.Net.WebSocket.csproj" />
    <ProjectReference Include="../../../../dnet-dctk/src/Discord.Net.Rest/Discord.Net.Rest.csproj" />
    <ProjectReference Include="../../../../dnet-dctk/src/Discord.Net.Webhook/Discord.Net.Webhook.csproj" />
    <ProjectReference Include="../../../../dnet-dctk/src/Discord.Net.Interactions/Discord.Net.Interactions.csproj" />
    <ProjectReference Include="../../../../dnet-dctk/src/Discord.Net.Commands/Discord.Net.Commands.csproj" />
    <ProjectReference Include="../../../../Discord.Addons.Hosting/Discord.Addons.Hosting.csproj" />
    <!-- <PackageReference Include="Discord.Addons.Hosting" Version="6.1.0"/> -->
    <PackageReference Include="EFCore.BulkExtensions" Version="8.1.1"/>
    <PackageReference Include="Google.Cloud.Vision.V1" Version="3.7.0"/>
    <PackageReference Include="GroqApiLibrary" Version="1.0.8" />
    <PackageReference Include="HarfBuzzSharp" Version="8.3.0-preview.4.1"/>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.0-preview.4.1"/>
    <PackageReference Include="LibGit2Sharp" Version="0.30.0"/>
    <PackageReference Include="MathNet.Symbolics" Version="0.25.0"/>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageReference Include="OpenAI" Version="2.1.0" />
    <PackageReference Include="OxyPlot.Core" Version="2.2.0"/>
    <PackageReference Include="OxyPlot.SkiaSharp" Version="2.2.0"/>
    <PackageReference Include="Polly" Version="8.5.0" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="9.0.0" />
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="1.4.0" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.2.0-beta.423"/>
    <PackageReference Include="Anilist4Net" Version="1.5.0"/>
    <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6"/>
    <PackageReference Include="CommandLineParser" Version="2.9.1"/>
    <PackageReference Include="CoreCLR-NCalc" Version="3.1.253" />
    <PackageReference Include="Fergun.Interactive" Version="1.8.0" />
    <PackageReference Include="Figgle" Version="0.5.1"/>
    <PackageReference Include="Genius.NET" Version="4.0.1"/>
    <PackageReference Include="GScraper" Version="1.1.3"/>
    <PackageReference Include="GTranslate" Version="2.2.8" />
    <PackageReference Include="Html2Markdown" Version="7.0.1.9" />
    <PackageReference Include="Humanizer" Version="3.0.0-beta.54"/>
    <PackageReference Include="JikanDotNet" Version="2.8.0" />
    <PackageReference Include="Google.Apis.Urlshortener.v1" Version="1.41.1.138"/>
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.68.0.3556" />
    <PackageReference Include="Google.Apis.Customsearch.v1" Version="1.49.0.2084"/>
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.66.0" />
    <PackageReference Include="Lavalink4NET.Discord.NET" Version="4.0.25" />
    <PackageReference Include="Lavalink4NET.Integrations.Lavasearch" Version="4.0.25" />
    <PackageReference Include="Lavalink4NET.Integrations.Lavasrc" Version="4.0.25" />
    <PackageReference Include="LazyCache" Version="2.4.0"/>
    <PackageReference Include="linq2db.EntityFrameworkCore" Version="8.1.0"/>
    <PackageReference Include="MartineApiNet" Version="1.0.14"/>
    <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta1"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.11.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="morelinq" Version="4.3.0" />
    <PackageReference Include="NekosBestApiNet" Version="1.0.7"/>
    <PackageReference Include="NHentaiAPI" Version="1.8.0"/>
    <PackageReference Include="NonBlocking" Version="2.1.2"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.8"/>
    <PackageReference Include="Octokit" Version="13.0.1" />
    <PackageReference Include="Otp.NET" Version="1.4.0"/>
    <PackageReference Include="PokeApiNet" Version="4.0.0"/>
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="Scrutor" Version="5.0.1" />
    <PackageReference Include="Serilog" Version="4.0.2" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
    <PackageReference Include="Serilog.Sinks.Seq" Version="8.0.0"/>
    <PackageReference Include="ServiceCollectionExtensions" Version="1.0.2"/>
    <PackageReference Include="SkiaSharp" Version="3.0.0-preview.3.1"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.0.0-preview.3.1"/>
    <PackageReference Include="SpotifyAPI.Web" Version="7.2.1" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.2.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.16" />
    <PackageReference Include="System.Text.Json" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.0-preview.5.24306.5"/>
    <PackageReference Include="System.IO.FileSystem.Watcher" Version="4.3.0"/>
    <PackageReference Include="System.Threading.Channels" Version="9.0.0-preview.5.24306.7"/>
    <PackageReference Include="System.ValueTuple" Version="4.5.0"/>
    <PackageReference Include="TwitchLib.Api" Version="3.10.0-preview-e47ba7f"/>
    <PackageReference Include="VirusTotalNet" Version="2.2.0"/>
    <PackageReference Include="YamlDotNet" Version="16.1.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="credentials.json"/>
    <None Include="..\..\.editorconfig" Link=".editorconfig"/>
    <None Update="data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_strings\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\tags.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="external\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="credentials.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Remove="DiscordChatExporter\Superpower.dll"/>
    <None Remove="DiscordChatExporter\Spectre.Console.dll"/>
    <None Remove="DiscordChatExporter\Polly.dll"/>
    <None Remove="DiscordChatExporter\MiniRazor.Runtime.dll"/>
    <None Remove="DiscordChatExporter\JsonExtensions.dll"/>
    <None Remove="DiscordChatExporter\Gress.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Core.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.runtimeconfig.json"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.exe"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.deps.json"/>
    <None Remove="DiscordChatExporter\CliFx.dll"/>
    <None Remove="data\http.txt"/>
    <Compile Update="Database\Migrations\PostgreSql\SeperateVcRoles.cs">
      <DependentUpon>SeparateVcRoles.Designer.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <NoWarn>CS8603,CS8601,CS8618,CS1998,CS8625,CS8604,CS0618,CS9113,CS4014,CS8509,CS8602,CS0168,CS0184,CS8600,CS8619,CS0649,CS0169,CS0067,CS1573,CS1572,CS1571,CS1574</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MewdekoSourceGen\MewdekoSourceGen.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />

    <AdditionalFiles Include="data\strings\responses\responses.en-US.json" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="credentials_example.json"/>
    <Content Update="gcreds.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
<!--  <ItemGroup>-->
<!--    <Reference Include="NHentaiAPI">-->
<!--      <HintPath>..\..\..\NHentaiAPI\NHentaiAPI\bin\Release\net8.0\NHentaiAPI.dll</HintPath>-->
<!--    </Reference>-->
<!--  </ItemGroup>-->

</Project>
