<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
    <OutputType>exe</OutputType>
    <RuntimeIdentifiers>win-x86;win-x64;linux-x64;linux-arm</RuntimeIdentifiers>
    <Nullable>annotations</Nullable>
    <EnablePreviewFeatures>True</EnablePreviewFeatures>
    <ApplicationIcon>Mewdeko.ico</ApplicationIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <WarningsAsErrors>CS1591</WarningsAsErrors>
    <PreferIQueryable>true</PreferIQueryable>

    <!-- .NET 9 Performance Optimizations -->
    <TieredPGO>true</TieredPGO>
    <OptimizationPreference>Speed</OptimizationPreference>
    <TieredCompilationQuickJitForLoops>true</TieredCompilationQuickJitForLoops>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Scripts\*.sql"/>
  </ItemGroup>


  <!--    DO NOT DELETE   -->
  <!--    happy pride 🏳️‍⚧️ 🏳️‍🌈-->

  <ItemGroup>
    <PackageReference Include="Claudia" Version="1.3.2"/>
    <PackageReference Include="dbup-postgresql" Version="7.0.1"/>
    <PackageReference Include="Discord.Net.WebSocket" Version="3.19.1"/>
    <PackageReference Include="Discord.Net.Rest" Version="3.19.1"/>
    <PackageReference Include="Discord.Net.Webhook" Version="3.19.1"/>
    <PackageReference Include="Discord.Net.Interactions" Version="3.19.1"/>
    <PackageReference Include="Discord.Net.Commands" Version="3.19.1"/>
    <PackageReference Include="Discord.Addons.Hosting" Version="6.1.0"/>
    <PackageReference Include="Figgle.Fonts" Version="0.6.6"/>
    <PackageReference Include="FluentMigrator" Version="8.0.1"/>
    <PackageReference Include="Google.Cloud.Vision.V1" Version="3.8.0"/>
    <PackageReference Include="GroqApiLibrary" Version="2.0.0"/>
    <PackageReference Include="HarfBuzzSharp" Version="8.3.1.5"/>
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.5"/>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4"/>
    <PackageReference Include="IF.Lastfm.Core" Version="1.0.0"/>
    <PackageReference Include="Inflatable.Lastfm" Version="1.2.0"/>
    <PackageReference Include="LibGit2Sharp" Version="0.31.0"/>
    <PackageReference Include="linq2db" Version="6.3.0"/>
    <PackageReference Include="MathNet.Symbolics" Version="0.25.0"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8"/>
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1"/>
    <PackageReference Include="morelinq" Version="4.4.0"/>
    <PackageReference Include="Npgsql" Version="10.0.3"/>
    <PackageReference Include="OpenAI" Version="2.11.0"/>
    <PackageReference Include="OxyPlot.Core" Version="2.2.0"/>
    <PackageReference Include="OxyPlot.SkiaSharp" Version="2.2.0"/>
    <PackageReference Include="Polly" Version="8.6.6"/>
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1"/>
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1"/>
    <PackageReference Include="Sentry.AspNetCore" Version="6.6.0"/>
    <PackageReference Include="Sentry.Serilog" Version="6.6.0"/>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.8"/>
    <PackageReference Include="ZiggyCreatures.FusionCache" Version="2.6.0"/>
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.4.0"/>
    <PackageReference Include="Anilist4Net" Version="1.5.0"/>
    <PackageReference Include="CodeHollow.FeedReader" Version="1.2.6"/>
    <PackageReference Include="CommandLineParser" Version="2.9.1"/>
    <PackageReference Include="CoreCLR-NCalc" Version="3.1.253"/>
    <PackageReference Include="Fergun.Interactive" Version="1.9.2"/>
    <PackageReference Include="Figgle" Version="0.6.6"/>
    <PackageReference Include="Genius.NET" Version="4.0.1"/>
    <PackageReference Include="GScraper" Version="1.2.1"/>
    <PackageReference Include="GTranslate" Version="2.3.1"/>
    <PackageReference Include="Html2Markdown" Version="7.1.2.20"/>
    <PackageReference Include="Humanizer" Version="3.0.10"/>
    <PackageReference Include="JikanDotNet" Version="2.10.4"/>
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.74.0.4162"/>
    <PackageReference Include="Google.Apis.Customsearch.v1" Version="1.49.0.2084"/>
    <PackageReference Include="Lavalink4NET.Discord.NET" Version="4.2.1"/>
    <PackageReference Include="Lavalink4NET.Integrations.Lavasearch" Version="4.2.1"/>
    <PackageReference Include="Lavalink4NET.Integrations.Lavasrc" Version="4.2.1"/>
    <PackageReference Include="LazyCache" Version="2.4.0"/>
    <PackageReference Include="MartineApiNet" Version="1.0.15"/>
    <PackageReference Include="MathNet.Numerics" Version="6.0.0-beta2"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.3.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.3.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.3.0"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NekosBestApiNet" Version="1.0.11"/>
    <PackageReference Include="NHentaiAPI" Version="1.8.0"/>
    <PackageReference Include="NonBlocking" Version="2.1.2"/>
    <PackageReference Include="Octokit" Version="14.0.0"/>
    <PackageReference Include="Otp.NET" Version="1.4.1"/>
    <PackageReference Include="PokeApiNet" Version="4.1.0"/>
    <PackageReference Include="QRCoder" Version="1.8.0"/>
    <PackageReference Include="Scrutor" Version="7.0.0"/>
    <PackageReference Include="Serilog" Version="4.3.1"/>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0"/>
    <PackageReference Include="ServiceCollectionExtensions" Version="1.0.2"/>
    <PackageReference Include="SkiaSharp" Version="3.119.4"/>
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="3.119.4"/>
    <PackageReference Include="SpotifyAPI.Web" Version="7.4.2"/>
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="7.4.2"/>
    <PackageReference Include="StackExchange.Redis" Version="2.13.17"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1"/>
    <PackageReference Include="System.Drawing.Common" Version="10.0.8"/>
    <PackageReference Include="TwitchLib.Api" Version="3.10.2"/>
    <PackageReference Include="VirusTotalNet" Version="2.2.0"/>
    <PackageReference Include="YamlDotNet" Version="18.0.0"/>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="credentials.json"/>
    <None Include="..\..\.editorconfig" Link=".editorconfig"/>
    <None Update="data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="_strings\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="certs\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\tags.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="external\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="credentials.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Remove="DiscordChatExporter\Superpower.dll"/>
    <None Remove="DiscordChatExporter\Spectre.Console.dll"/>
    <None Remove="DiscordChatExporter\Polly.dll"/>
    <None Remove="DiscordChatExporter\MiniRazor.Runtime.dll"/>
    <None Remove="DiscordChatExporter\JsonExtensions.dll"/>
    <None Remove="DiscordChatExporter\Gress.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Core.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.runtimeconfig.json"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.exe"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.dll"/>
    <None Remove="DiscordChatExporter\DiscordChatExporter.Cli.deps.json"/>
    <None Remove="DiscordChatExporter\CliFx.dll"/>
    <None Remove="data\http.txt"/>
    <None Remove="data\strings\responses\unused_keys.txt"/>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <NoWarn>CS8603,CS8601,CS8618,CS1998,CS8625,CS8604,CS0618,CS9113,CS4014,CS8509,CS8602,CS0168,CS0184,CS8600,CS8619,CS0649,CS0169,CS0067,CS1573,CS1572,CS1571,CS1574</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MewdekoSourceGen\MewdekoSourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>

    <AdditionalFiles Include="data\strings\responses\en-US\*.json"/>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="credentials_example.json"/>
    <Content Update="gcreds.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="credentials.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="data\strings\commands\"/>
    <Folder Include="Modules\Currency\Common\"/>
    <Folder Include="Modules\Xp\Extensions\"/>
  </ItemGroup>
  <!--  <ItemGroup>-->
  <!--    <Reference Include="NHentaiAPI">-->
  <!--      <HintPath>..\..\..\NHentaiAPI\NHentaiAPI\bin\Release\net8.0\NHentaiAPI.dll</HintPath>-->
  <!--    </Reference>-->
  <!--  </ItemGroup>-->

</Project>
