// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Mewdeko.Database.Migrations
{
    [DbContext(typeof(MewdekoContext))]
    [Migration("AddCommandStats")]
    partial class AddCommandStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // required for reasons
        }
    }
}