// <auto-generated-ish/>

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Mewdeko.Database.Migrations.SQLite
{
    [DbContext(typeof(MewdekoSqLiteContext))]
    [Migration("CtPrefixes")]
    partial class CtPrefixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // required for reasons
        }
    }
}