// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Mewdeko.Database.Migrations.SQLite
{
    [DbContext(typeof(MewdekoSqLiteContext))]
    [Migration("SwitchFcInProfile")]
    partial class SwitchFcInProfile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // required for reasons
        }
    }
}
