// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("antimasspostsettings")]
	public class AntiMassPostSetting
	{
		[Column("id"                        , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                         { get; set; } // integer
		[Column("guildid"                                                                                                 )] public ulong     GuildId                    { get; set; } // numeric(20,0)
		[Column("action"                                                                                                  )] public int       Action                     { get; set; } // integer
		[Column("channelthreshold"                                                                                        )] public int       ChannelThreshold           { get; set; } // integer
		[Column("timewindowseconds"                                                                                       )] public int       TimeWindowSeconds          { get; set; } // integer
		[Column("contentsimilaritythreshold"                                                                              )] public double    ContentSimilarityThreshold { get; set; } // double precision
		[Column("mincontentlength"                                                                                        )] public int       MinContentLength           { get; set; } // integer
		[Column("checklinksonly"                                                                                          )] public bool      CheckLinksOnly             { get; set; } // boolean
		[Column("checkduplicatecontent"                                                                                   )] public bool      CheckDuplicateContent      { get; set; } // boolean
		[Column("requireidenticalcontent"                                                                                 )] public bool      RequireIdenticalContent    { get; set; } // boolean
		[Column("casesensitive"                                                                                           )] public bool      CaseSensitive              { get; set; } // boolean
		[Column("deletemessages"                                                                                          )] public bool      DeleteMessages             { get; set; } // boolean
		[Column("notifyuser"                                                                                              )] public bool      NotifyUser                 { get; set; } // boolean
		[Column("punishduration"                                                                                          )] public int       PunishDuration             { get; set; } // integer
		[Column("roleid"                                                                                                  )] public ulong?    RoleId                     { get; set; } // numeric(20,0)
		[Column("ignorebots"                                                                                              )] public bool      IgnoreBots                 { get; set; } // boolean
		[Column("maxmessagestracked"                                                                                      )] public int       MaxMessagesTracked         { get; set; } // integer
		[Column("dateadded"                                                                                               )] public DateTime? DateAdded                  { get; set; } // timestamp

		#region Associations
		/// <summary>
		/// FK_AntiMassPostIgnoredRole_AntiMassPostSetting_AntiMassPostSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiMassPostIgnoredRole.AntiMassPostSettingId))]
		public IEnumerable<AntiMassPostIgnoredRole> AntiMassPostIgnoredRoles { get; set; } = null!;

		/// <summary>
		/// FK_AntiMassPostIgnoredUser_AntiMassPostSetting_AntiMassPostSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiMassPostIgnoredUser.AntiMassPostSettingId))]
		public IEnumerable<AntiMassPostIgnoredUser> AntiMassPostIgnoredUsers { get; set; } = null!;

		/// <summary>
		/// FK_AntiMassPostIgnoredChannel_AntiMassPostSetting_AntiMassPostSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiMassPostIgnoredChannel.AntiMassPostSettingId))]
		public IEnumerable<AntiMassPostIgnoredChannel> AntiMassPostIgnoredChannels { get; set; } = null!;

		/// <summary>
		/// FK_AntiMassPostLinkWhitelist_AntiMassPostSetting_AntiMassPostSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiMassPostLinkWhitelist.AntiMassPostSettingId))]
		public IEnumerable<AntiMassPostLinkWhitelist> AntiMassPostLinkWhitelists { get; set; } = null!;

		/// <summary>
		/// FK_AntiMassPostLinkBlacklist_AntiMassPostSetting_AntiMassPostSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiMassPostLinkBlacklist.AntiMassPostSettingId))]
		public IEnumerable<AntiMassPostLinkBlacklist> AntiMassPostLinkBlacklists { get; set; } = null!;
		#endregion
	}
}
