// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("antimasspostlinkblacklist")]
	public class AntiMassPostLinkBlacklist
	{
		[Column("id"                     , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id                      { get; set; } // integer
		[Column("antimasspostsettingid"                                                                                    )] public int       AntiMassPostSettingId   { get; set; } // integer
		[Column("domain"                                                                                                   )] public string    Domain                  { get; set; } = null!; // text
		[Column("dateadded"                                                                                                )] public DateTime? DateAdded               { get; set; } // timestamp
	}
}
