// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("antipostchannelsettings")]
	public class AntiPostChannelSetting
	{
		[Column("id"             , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id              { get; set; } // integer
		[Column("guildid"                                                                                         )] public ulong     GuildId         { get; set; } // numeric(20,0)
		[Column("action"                                                                                          )] public int       Action          { get; set; } // integer
		[Column("deletemessages"                                                                                  )] public bool      DeleteMessages  { get; set; } // boolean
		[Column("notifyuser"                                                                                      )] public bool      NotifyUser      { get; set; } // boolean
		[Column("punishduration"                                                                                  )] public int       PunishDuration  { get; set; } // integer
		[Column("roleid"                                                                                          )] public ulong?    RoleId          { get; set; } // numeric(20,0)
		[Column("ignorebots"                                                                                      )] public bool      IgnoreBots      { get; set; } // boolean
		[Column("dateadded"                                                                                       )] public DateTime? DateAdded       { get; set; } // timestamp

		#region Associations
		/// <summary>
		/// FK_AntiPostChannelChannel_AntiPostChannelSetting_AntiPostChannelSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiPostChannelChannel.AntiPostChannelSettingId))]
		public IEnumerable<AntiPostChannelChannel> AntiPostChannelChannels { get; set; } = null!;

		/// <summary>
		/// FK_AntiPostChannelIgnoredRole_AntiPostChannelSetting_AntiPostChannelSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiPostChannelIgnoredRole.AntiPostChannelSettingId))]
		public IEnumerable<AntiPostChannelIgnoredRole> AntiPostChannelIgnoredRoles { get; set; } = null!;

		/// <summary>
		/// FK_AntiPostChannelIgnoredUser_AntiPostChannelSetting_AntiPostChannelSettingId backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(AntiPostChannelIgnoredUser.AntiPostChannelSettingId))]
		public IEnumerable<AntiPostChannelIgnoredUser> AntiPostChannelIgnoredUsers { get; set; } = null!;
		#endregion
	}
}
