// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("BotInstances")]
	public class BotInstance
	{
		[Column("Id"              , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int       Id               { get; set; } // integer
		[Column("BotName"         , CanBeNull    = false                                                             )] public string    BotName          { get; set; } = null!; // text
		[Column("DateAdded"                                                                                          )] public DateTime? DateAdded        { get; set; } // timestamp (6) without time zone
		[Column("BotAvatar"       , CanBeNull    = false                                                             )] public string    BotAvatar        { get; set; } = null!; // text
		[Column("BotId"                                                                                              )] public ulong   BotId            { get; set; } // numeric(20,0)
		[Column("IsActive"                                                                                           )] public bool      IsActive         { get; set; } // boolean
		[Column("LastStatusUpdate"                                                                                   )] public DateTime  LastStatusUpdate { get; set; } // timestamp (6) without time zone
		[Column("Port"                                                                                               )] public int       Port             { get; set; } // integer
		[Column("Host"            , CanBeNull    = false                                                             )] public string    Host             { get; set; } = "localhost"; // text
	}
}
