// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	/// <summary>
	///     Represents a COPR project monitor configuration for a Discord guild.
	/// </summary>
	[Table("coprmonitors")]
	public class CoprMonitor
	{
		/// <summary>
		///     Gets or sets the unique identifier for this monitor.
		/// </summary>
		[Column("id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int Id { get; set; } // integer

		/// <summary>
		///     Gets or sets the guild ID where this monitor is configured.
		/// </summary>
		[Column("guildid")] public ulong GuildId { get; set; } // numeric(20,0)

		/// <summary>
		///     Gets or sets the channel ID where notifications will be posted.
		/// </summary>
		[Column("channelid")] public ulong ChannelId { get; set; } // numeric(20,0)

		/// <summary>
		///     Gets or sets the COPR project owner (user or @group).
		/// </summary>
		[Column("coprowner")] public string CoprOwner { get; set; } = null!; // text

		/// <summary>
		///     Gets or sets the COPR project name.
		/// </summary>
		[Column("coprproject")] public string CoprProject { get; set; } = null!; // text

		/// <summary>
		///     Gets or sets whether this monitor is enabled.
		/// </summary>
		[Column("isenabled")] public bool IsEnabled { get; set; } // boolean

		/// <summary>
		///     Gets or sets the package filter (comma-separated package names, or null for all).
		/// </summary>
		[Column("packagefilter")] public string? PackageFilter { get; set; } // text

		/// <summary>
		///     Gets or sets whether to notify on succeeded builds.
		/// </summary>
		[Column("notifyonsucceeded")] public bool NotifyOnSucceeded { get; set; } // boolean

		/// <summary>
		///     Gets or sets whether to notify on failed builds.
		/// </summary>
		[Column("notifyonfailed")] public bool NotifyOnFailed { get; set; } // boolean

		/// <summary>
		///     Gets or sets whether to notify on canceled builds.
		/// </summary>
		[Column("notifyoncanceled")] public bool NotifyOnCanceled { get; set; } // boolean

		/// <summary>
		///     Gets or sets whether to notify on pending builds.
		/// </summary>
		[Column("notifyonpending")] public bool NotifyOnPending { get; set; } // boolean

		/// <summary>
		///     Gets or sets whether to notify on running builds.
		/// </summary>
		[Column("notifyonrunning")] public bool NotifyOnRunning { get; set; } // boolean

		/// <summary>
		///     Gets or sets whether to notify on skipped builds.
		/// </summary>
		[Column("notifyonskipped")] public bool NotifyOnSkipped { get; set; } // boolean

		/// <summary>
		///     Gets or sets the custom message for succeeded builds.
		/// </summary>
		[Column("succeededmessage")] public string? SucceededMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the custom message for failed builds.
		/// </summary>
		[Column("failedmessage")] public string? FailedMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the custom message for canceled builds.
		/// </summary>
		[Column("canceledmessage")] public string? CanceledMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the custom message for pending builds.
		/// </summary>
		[Column("pendingmessage")] public string? PendingMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the custom message for running builds.
		/// </summary>
		[Column("runningmessage")] public string? RunningMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the custom message for skipped builds.
		/// </summary>
		[Column("skippedmessage")] public string? SkippedMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the default message for other build statuses.
		/// </summary>
		[Column("defaultmessage")] public string? DefaultMessage { get; set; } // text

		/// <summary>
		///     Gets or sets the date this monitor was added.
		/// </summary>
		[Column("dateadded")] public DateTime? DateAdded { get; set; } // timestamp (6) without time zone
	}
}
