// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TtsUserSettings")]
	public class TtsUserSetting
	{
		[Column("Id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int    Id        { get; set; } // integer
		[Column("GuildId"                                                                                    )] public ulong  GuildId   { get; set; } // numeric(20,0)
		[Column("UserId"                                                                                     )] public ulong  UserId    { get; set; } // numeric(20,0)
		[Column("Voice"                                                                                      )] public string? Voice     { get; set; } // text
		[Column("IsBlocked"                                                                                  )] public bool   IsBlocked { get; set; } // boolean
	}
}
